spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATABASE_USERNAME}
    url: ${SPRING_DATABASE_URL}
    password: ${SPRING_DATABASE_PASSWORD}
  application:
    name: shop
  jpa:
    properties:
      hibernate:
        show_sql: 'true'
    hibernate:
      ddl-auto: update